name: Sync with template

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Template Sync
        uses: AndreasAugustin/actions-template-sync@v2.4.2
        with:
          source_repo_path: "alshedivat/al-folio.git"
          source_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
